---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: openjdk-8

params:
  DEBUG:

inputs:
  - name: pipelines-repo
  - name: project-repo

run:
  path: pipelines-repo/tasks/gradlew-test/task.sh
