---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  DEBUG:
  FILENAME:
  TARGET:

inputs:
- name: pipelines-repo
- name: source
- name: destination

run:
  path: pipelines-repo/tasks/copy-path/task.sh
